name: CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: py39-test
        - linux: py311-test
        - linux: py313-test
        - macos: py310-test
        - macos: py312-test
        - macos: py313-test
        - windows: py310-test
        - windows: py312-test
        - windows: py313-test
        - linux: lint
          pytest: false
        - linux: docs
          pytest: false
        - linux: py311-integration
        - macos: py312-integration
        - windows: py313-integration

  build:
    needs: [test]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@main
    with:
      upload_to_pypi: false
      save_artifacts: true

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist/
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
